# Generated by Django 4.0.6 on 2022-09-01 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='id_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.produto'),
        ),
    ]
