# Generated by Django 4.0.6 on 2022-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=25)),
                ('bpm', models.IntegerField()),
                ('tom', models.CharField(max_length=3)),
            ],
        ),
    ]
