# Generated by Django 4.0.6 on 2022-08-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%y/%m/%d/'),
        ),
    ]
