# Generated by Django 4.0.6 on 2022-08-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
